elhub/devxp-lint-configuration

resources/.golangci.yml, resources/.mega-linter.yml
Testing:
- Test Command: 
Documentation:
- No updates
=> "Remove shadowing for err/ctx"

Makefile
Issue ID(s): TDX-514
Testing:
- Test Command: make check'
Documentation:
- No updates
=> Add jfrog repository to NPX commands

resources/.mega-linter.yml
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
=> Remove Spell

.editorconfig, .gitignore, resources/.yamllint.yml
Issue ID(s): TDX-598
Testing:
Documentation:
- No updates
=> Fix ansible-lint support

resources/.yamllint.yml
Issue ID(s): TDX-598
Testing:
Documentation:
- No updates
=> Improve ansible synchronization

resources/.ansible-lint
Issue ID(s): TDX-598
Testing:
Documentation:
- No updates
=> Fix empty ansible-lint file

.gitignore
🚩🚩🚩 **This PR has not been linted!**
Testing:
Documentation:
- No updates
=> add the python lint configs to gitignore

resources/.mega-linter.yml
=> fix: change branch in ktlint pre command

resources/.ansible-lint
=> fix: make .ansible-lint pass ansible-lint

.github/CODEOWNERS, .teamcity/pom.xml, resources/.ecrc, resources/.gitleaks.toml, resources/.secretlintrc.json, resources/trivy.yaml
Added lint configs for
* editorconfig linter
* gitleaks
* secretlint
* trivy
=> Add new lint configurations

resources/.mega-linter.yml, resources/checkstyle-config.xml, resources/java-pmd-ruleset.xml
* resources/checkstyle-config.xml is copied from devxp-ansible-collection-wsl
* resources/java-pmd-ruleset.xml is the default config with an exception added for requiring a constructor for every class
=> Add java linting config

resources/.mega-linter.yml
We find that wget does not seem to correctly pick up proxy related environment variables, so we're replacing wget calls with curl
=> Replace wget with curl in rule fetching

resources/.mega-linter.yml
=> Java checkstyle config file location change

resources/.mega-linter.yml
=> Fix the Java Check Style Path

resources/.mega-linter.yml
=> fix java checkstyle lint

.github/renovate.json
=> Enable Renovate scanning for devxp-lint-configuration

resources/.detekt.yml
=> fix: loosen detekt rules

resources/.gitleaks.toml
=> fix: add gitleaks exception for encrypted TeamCity credentials

resources/.flake8
=> Ignore flake8 E203

resources/.mega-linter.yml
Attempt to force flake8 to respect the max line length. The config file
doesn't work (seems to be a known issue).
=> Set flake8 parameter

.teamcity/settings.kts, resources/.editorconfig-checker.json, resources/.mega-linter.yml, resources/.prettierrc.json
* Fix and rename .ecrc
* Remove deprecated jsxBracketSameLine
=> Fix and rename .ecrc file
